### ISSUE TITLE
Portals being deleted after server restart

### ISSUE THREAD

**Issue by hugeblank** [trentech/ProjectPortals#68]
Software info:
- spongeforge-1.11.2-2393-6.1.0-BETA-2471
- project portals-6.1.0-0.14.0
- project core-6.1.0-0.1.0
- forge-1.11.2-13.20.1.2393

Issue:
Every time I create a portal and restart the server, the portal gets deleted. I have tried to delete the pjp config and all that, but the issue persists.

**Comment by WindRider739** [comment]
I am also having this problem.

**Comment by hugeblank** [comment]
@trentech So I'm taking a complete shot in the dark here, as in I have no real Java experience. I'm guessing the source of the issue is on line 111 of /pjp/portal/PortalService.java which reads:
```PreparedStatement statement = connection.prepareStatement("SELECT * _FROM_ " + sqlManager.getPrefix("PORTALS"));```

Judging by a couple of lines below on line 213 where it says:
```PreparedStatement statement = connection.prepareStatement("DELETE _from_ " + sqlManager.getPrefix("PORTALS") + " WHERE Name = ?");```

I think maybe you mean for that "FROM" on line 111 to be lowercased?

**Comment by hugeblank** [comment]
Backporting to 13.7 seems to work, although that is for API 5.2.0... @WindRider739 you may want to know about this :P

**Comment by n00b42** [comment]
```
forge-1.12.2-14.23.0.2491
spongeforge-1.12.2-2503-7.0.0-BETA-2705
projectcore-7.0.0-0.2.0.jar
projectportals-7.0.0-0.14.0.jar
```

Issue still there, server starts fine when db is deleted, but after saving a portal and restarting the server it throws this error:

> [01:03:58] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=pjp, name=ProjectPortals, version=0.14.0, description=One stop shop for all things portal, url=http://github.com/TrenTech/ProjectPortals, authors=[TrenTech], source=/dwe/minecraft/forge/./mods/plugins/projectportals-7.0.0-0.14.0.jar}
> java.util.NoSuchElementException: No value present
>         at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_141]
>         at com.gmail.trentech.pjp.portal.Portal.deserialize(Portal.java:291) ~[Portal.class:?]
>         at com.gmail.trentech.pjp.portal.PortalService.init(PortalService.java:119) ~[PortalService.class:?]
>         at com.gmail.trentech.pjp.Main.onStartedServer(Main.java:166) ~[Main.class:?]

**Comment by n00b42** [comment]
Ok, I figured out the problem:
```
<Portal.java>
return Sponge.getDataManager().deserialize(Portal.class, DataFormats.JSON.read(portal)).get();
```
The deserialize function needs to know the correct class.
As "Portal" is only the parent class and its child classes "Local/Server" have different fields (at least "Local" has), the deserialization fails.

Replacing "Portal.class" by "Local.class" solved it for me as I currently only have "Local" portals.

To solve the issue, you could either merge Local and Server classes together and distinguish them otherwise, or (better) store the correct class alongside the serialized data as another field (like you already do with the name of the portal)

Regards

**Comment by Krosta8** [comment]
It would be very nice to be able to create portals again and with no problem on server start. I "understand" what did you write, but I don't have enough experience to be albe to do it on my own. Can you, please, send me your "updated" version? I would be very grateful.

**Comment by n00b42** [comment]
I made a somewhat proper fix now, I would prefer if trentech could accept the merge and provide the update himself, that way there would be no other version around.

This fix still requires to remove the db file before working as the data structure changed. I first tried to have some migration/update code in it as well, but that would be some hacky one-time-used-only code, therefore I decided to leave that and better "start fresh"

**Comment by fboyd** [comment]
I just started using ProjectPortals today with Forge and Sponge, I was going to open this issue up but thankfully people are right on track and working :-)  
Just adding my 2 cents I'm in the same boat as other people with the issue.

**Comment by trentech** [comment]
Resolved 8ed81916c0db6f49882ccf12e49c3afac5db9998
Might need to clear your databases

**Comment by fboyd** [comment]
@trentech 
I don't want to make a duplicate Issue, but I have the exact problem listed and it is not fixed from my point of view.  Let me give the details.  Your commit references before is for v7 API while I am running v5.
See info below.  Clean brand new server build and install.  No pre-existing database.
Server:
Java:
> java version "1.8.0_66"
> Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

MineCraft &Mods Versions:
> MineCraft 1.11.2
> spongeforge-1.11.2-2476-6.1.0-BETA-2715
> forge-1.11.2-13.20.1.2476
> justenoughdimensions-1.11.2-1.6.0-dev.20171107.235423 [JED Latest ](https://masa.dy.fi/tmp/minecraft/jed/1.6.0-dev/)
> projectcore-5.2.0-0.1.5
> projectportals-5.2.0-0.13.8

JED Command to create Dimension
> /jed dimbuilder clear
> /jed dimbuilder dimtype 1100 tmpname _dim1100 false WorldProviderSurfaceJED
> /jed dimbuilder set name Creative_1100
> /jed dimbuilder set generatorName default
> /jed dimbuilder set RandomSeed -4799909556600174584
> /jed dimbuilder set keepInventory true
> /jed dimbuilder set mobGriefing false
> /jed dimbuilder set Difficulty 1
> /jed dimbuilder set SpawnX 732
> /jed dimbuilder set SpawnY 65
> /jed dimbuilder set SpawnZ 306
> /jed dimbuilder create-as 1100

On my desktop I installed Minecraft Launcher, Java 8.144, and installed the same Forge and mods except of course Sponge don't need on the client side.

The reason I am using the older Forge is for Sponge, because I am trying to use GriefPrevention and LuckPerms, and of course ProjectPortals.  v7 of Sponge from what I saw is on a much older version of Forge which is incompatible with mods I am using.
But in this case, I simply used the bare minimum.
I create the portals between dimensions just peachy and they work fine.  I logout / login and they are fine.  I restart the server, boom gone, run a `portal list` and it is empty.

The server restart I get this right after it is `*done*`
https://pastebin.com/2BAEGKRj

I'm not a Java programmer so I'm no help there, but I can put my server on the net if you want to see for yourself, but I'd appreciate any help, I love this plugin, and I just got Matti, the dev of JustEnoughDimensions to fix up that mod to work with Sponge.

Let me know whatever I can do to help, I'd appreciate any help in resolving this.
Thanks!
-Frank
